# Generated by Django 5.0.1 on 2024-01-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_rename_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(default=1, max_length=255, verbose_name='Направление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mount',
            field=models.CharField(default=1, max_length=255, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя студента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='geek_coins_balance',
            field=models.IntegerField(default=4),
        ),
    ]
