# Generated by Django 5.0.1 on 2024-01-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_remove_user_user_user_direction_user_mount_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='coin',
        ),
    ]
