# Generated by Django 5.0.1 on 2024-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rename_amount_transaction_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='geek_coins_balance',
            field=models.IntegerField(default=0),
        ),
    ]
