# Generated by Django 5.0.1 on 2024-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_alter_user_geek_coins_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('payroll', 'Payroll'), ('burn', 'Burn'), ('debit', 'Debit'), ('credit', 'Credit')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
